export const COLLECTIONS = {
  USERS: 'users',
  ORGANIZATIONS: 'organizations',
  WORKSPACES: 'workspaces',
  MODULES: 'modules',
  MAIN_TABS: 'mainTabs',
  SUB_TABS: 'subTabs',
  ENTITIES: 'entities',
  PROJECTS: 'projects',
  TASKS: 'tasks',
  SUB_TASKS: 'subTasks',
  ACTIVITY_LOGS: 'activityLogs',
  NOTIFICATIONS: 'notifications',
  EXPENSES: 'expenses',
  INCOME: 'income',
  GOALS: 'goals',
  DOCUMENTS: 'documents',
  ATTACHMENTS: 'attachments',
  COMMENTS: 'comments',
  CALENDAR_EVENTS: 'calendarEvents',
  MEETINGS: 'meetings',
  SCRAPED_COMPETITIONS: 'scrapedCompetitions',
  AUTOMATIONS: 'automations',
} as const;
